import type { Metadata } from "next";
import { Geist, Geist_Mono, Montserrat, Roboto } from "next/font/google";
import "./globals.css";

const geistMontserrat = Montserrat({
  variable: "--font-montserrat",
  subsets: ["latin"],
});

const geistRoboto = Roboto({
  variable: "--font-roboto",
  subsets: ["latin"],
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
//   other: {
//     "font-preload": `
//       <link rel="preload" href="/_next/static/media/Montserrat-latin.woff2" as="font" type="font/woff2" crossorigin>
//     `,
//   },
// };

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  themeColor: "#EFF6FF", // Usa el HEX de tu color de fondo (ej. bg-blue-50 = #EFF6FF)
  other: {
    "font-preload": `
      <link rel="preload" href="/_next/static/media/Montserrat-latin.woff2" as="font" type="font/woff2" crossorigin>
    `,
    // Meta tags para móviles
    "mobile-web-app-capable": "yes",
    "apple-mobile-web-app-capable": "yes",
    "apple-mobile-web-app-status-bar-style": "black-translucent",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html className="md:h-full" lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${geistRoboto.variable} ${geistMontserrat.variable}  antialiased flex flex-col h-full`}
      >
        {/* Barra de estado personalizada */}
        {children}
      </body>
    </html>
  );
}
